[package]
name = "sevenfold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.8"
nom = "7.1.1"
regex = "1.7.0"
unstringify = "0.1.4"

[build-dependencies]
lalrpop = "0.19.7"
